# Generated by Django 4.0.3 on 2022-03-16 02:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='lead',
            old_name='emai',
            new_name='email',
        ),
    ]
